print(" ________________________________________ ")
print("/     Long live the Revolution!          \ ")
print("\                                        / ")
print(" ---------------------------------------- ")
print("        \   ^__^ ")
print("         \  (oo)\_______ ")
print("            (__)\       )\/\ ")
print("                ||----w | ")
print("                ||     || ")